name: D++ CI
on: [push, pull_request]

jobs:
  linux:
    name: Linux ${{matrix.cfg.arch}} (${{matrix.cfg.cpp-version}})
    runs-on: ${{matrix.cfg.os}}
    strategy:
      fail-fast: false # Don't fail everything if one fails. We want to test each OS/Compiler individually
      matrix:
        cfg:
          - { arch: 'amd64', os: ubuntu-20.04, cpp-version: g++-8 }
          - { arch: 'amd64', os: ubuntu-20.04, cpp-version: g++-9 }

    steps:
      - name: Checkout D++
        uses: actions/checkout@v2

      - name: Install apt packages
        run: sudo dpkg --add-architecture i386 && sudo apt update && sudo apt install  ${{ matrix.cfg.cpp-version }}:${{ matrix.cfg.arch }} ninja-build libsodium-dev:${{ matrix.cfg.arch }} libopus-dev:${{ matrix.cfg.arch }} zlib1g-dev:${{ matrix.cfg.arch }}

      - name: Generate CMake
        run: mkdir build && cd build && cmake -G Ninja ..
        env:
          CXX: ${{matrix.cfg.cpp-version}}

      - name: Build Project
        run: cd build && ninja

      - name: Package distributable
        if: ${{ matrix.cfg.cpp-version == 'g++-8' }}
        run: cd build && cpack

      - name: Upload Binary
        if: ${{ matrix.cfg.cpp-version == 'g++-8' }}
        uses: actions/upload-artifact@v2
        with:
          name: "libdpp - Debian Package ${{matrix.cfg.arch}}"
          path: '${{github.workspace}}/build/*.deb'

  macos:
    name: macOS x64
    runs-on: macos-latest
    steps:
      - name: Checkout D++
        uses: actions/checkout@v2

      - name: Install homebrew packages
        run: brew install cmake ninja libsodium opus

      - name: Generate CMake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -G Ninja ..

      - name: Build Project
        run: cd build && ninja

  windows: # Windows x64 and x86 build matrix
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        cfg:
        - { name: x64,  arch: x64, config: Release }
        - { name: x64,  arch: x64, config: Debug }

    name: "Windows ${{matrix.cfg.name}}-${{matrix.cfg.config}}"
    runs-on: windows-2019
    steps:
      - name: Checkout D++
        uses: actions/checkout@v2
        with:
          path: main

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install chocolatey packages (x64)
        run: choco install ninja -y

      - name: Generate CMake
        run: mkdir main/build && cd main/build && cmake -G "Visual Studio 16 2019" ..

      - name: Build Project
        run: cmake --build main/build --target dpp --config ${{matrix.cfg.config}}

      - name: Package distributable
        run: cd main/build && cpack

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: "libdpp - Windows ${{matrix.cfg.name}}-${{matrix.cfg.config}}"
          path: '${{github.workspace}}/main/build/*.zip'

  cross-compiles:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - {name: "ARM64", arch: arm64, packages: gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu, path-prefix: aarch64-linux-gnu, cmake-options: -DCMAKE_TOOLCHAIN_FILE=cmake/ARM64ToolChain.cmake, spec-repo: true}
          - {name: "ARMHF", arch: armhf, packages: gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf, path-prefix: arm-linux-gnueabihf, cmake-options: -DCMAKE_TOOLCHAIN_FILE=cmake/ARMHFToolChain.cmake, spec-repo: true}
          - {name: "Linux x86", arch: i386, packages: 'g++-8 gcc-8-multilib glibc-*:i386 libc6-dev-i386 g++-8-multilib', path-prefix: i386-linux-gnu, cmake-options: -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_CXX_FLAGS=-m32 -DCPACK_PACKAGE_ARCHITECTURE=i386, spec-repo: false}

    name: ${{matrix.cfg.name}}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout D++
        uses: actions/checkout@v2

      - name: Setup ${{matrix.cfg.name}} Repositories 
        if: ${{matrix.cfg.spec-repo == true}}
        run: printf "deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main multiverse restricted universe\ndeb [arch=${{matrix.cfg.arch}}] http://ports.ubuntu.com/ubuntu-ports/ focal main multiverse restricted universe\ndeb [arch=${{matrix.cfg.arch}}] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main multiverse restricted universe\ndeb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal-updates main multiverse restricted universe\ndeb [arch=amd64] http://security.ubuntu.com/ubuntu/ focal-security main multiverse restricted universe" > a && sudo mv a /etc/apt/sources.list

      - name: Install Packages
        run: sudo dpkg --add-architecture ${{matrix.cfg.arch}} && sudo apt update && sudo apt install -y zlib1g-dev:${{matrix.cfg.arch}} libssl-dev:${{matrix.cfg.arch}} ${{matrix.cfg.packages}} ninja-build libopus-dev:${{matrix.cfg.arch}} libsodium-dev:${{matrix.cfg.arch}} 

      - name: Prepare System for CMake
        run: export PATH=$PATH:/usr/include:/usr/lib/${{matrix.cfg.path-prefix}}/:/usr/bin && sudo mv /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/ && sudo rm /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libcrypto.a /usr/lib/x86_64-linux-gnu/libssl.a && sudo mv /usr/lib/${{matrix.cfg.path-prefix}}/pkgconfig/libsodium.pc /usr/lib/pkgconfig/

      - name: Generate CMakeFiles
        run: mkdir build && cd build && cmake ${{matrix.cfg.cmake-options}} -DCMAKE_BUILD_TYPE=Release -G Ninja ..

      - name: Compile Source
        run: cd build && sudo ninja

      - name: Package Distributable
        run: cd build && cpack

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: "libdpp - Debian Package ${{matrix.cfg.name}}"
          path: "${{github.workspace}}/build/*.deb"


