name: Library Binaries Update
on: [push]
  branches: [master]

jobs:
  updater:
    name: Update windows bot template
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false # Don't fail everything if one fails.

    needs: [linux, windows, macos, cross-compiles]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Run workflow dispatch
        run: gh workflow run brainboxdotcc/windows-bot-template "Library Binaries Update"

